apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spawnta-project
  namespace: argocd
spec:
  description: Project for Spawnta application services
  sourceRepos:
  - '*'
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
