apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aymanesbe3/spawnta-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_FLYWAY_ENABLED
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: SPRING_FLYWAY_ENABLED
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: DB_HOST
          value: "postgres"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/spawnta"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: POSTGRES_PASSWORD
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
        - name: SPRING_DATA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: REDIS_PASSWORD
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_APP_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: JWT_SECRET
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: CLOUDINARY_API_SECRET
        - name: SPRING_MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: MAIL_HOST
        - name: SPRING_MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: MAIL_PORT
        - name: SPRING_MAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: MAIL_USERNAME
        - name: SPRING_MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: MAIL_PASSWORD
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            configMapKeyRef:
              name: spawnta-config
              key: STRIPE_PUBLISHABLE_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: STRIPE_SECRET_KEY
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: spawnta-secrets
              key: STRIPE_WEBHOOK_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
