apiVersion: v1
kind: Secret
metadata:
  name: spawnta-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_WITH_YOUR_DB_PASSWORD"
  REDIS_PASSWORD: "REPLACE_WITH_YOUR_REDIS_PASSWORD"
  JWT_SECRET: "REPLACE_WITH_YOUR_JWT_SECRET"
  CLOUDINARY_API_KEY: "REPLACE_WITH_YOUR_KEY"
  CLOUDINARY_API_SECRET: "REPLACE_WITH_YOUR_SECRET"
  MAIL_PASSWORD: "REPLACE_WITH_YOUR_MAIL_APP_PASSWORD"
  STRIPE_SECRET_KEY: "REPLACE_WITH_YOUR_STRIPE_SK_TEST"
  STRIPE_WEBHOOK_SECRET: "REPLACE_WITH_YOUR_STRIPE_WEBHOOK_SECRET"
