name: Deploy

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: aymanesbe3

jobs:

  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-backend:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-frontend:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-frontend:latest

      - name: Build & push admin
        uses: docker/build-push-action@v5
        with:
          context: ./admin
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-admin:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-admin:latest

      - name: Build & push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./devops/nginx
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-nginx:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_USERNAME }}/spawnta-nginx:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          use_insecure_cipher: true
          script: |
            cd /home/ec2-user/spawnta
            docker compose \
              -f docker-compose.yml \
              -f docker-compose.prod.yml \
              pull
            docker compose \
              -f docker-compose.yml \
              -f docker-compose.prod.yml \
              up -d --remove-orphans
            docker image prune -f